### ISSUE TITLE
[question] gzip auto-compression 

### ISSUE THREAD

**Issue by jingpengw** [JuliaCloud/GoogleCloud.jl#17]
it looks like there is only one place that use the Libz to compress the data.
https://github.com/joshbode/GoogleCloud.jl/blob/1dbf42410884a3a4895e8e5ea03c610917b264e3/src/api/api.jl#L252

With the gzip Content-Compression flag, it will be automatically decompressed on the server side, right?
if so, it is not very efficient to fully use the bandwidth. Can I decompress it on the client side?

**Comment by joshbode** [comment]
I believe it comes back still gzipped (that was the intention!), and the decompression should be occurring in `Requests.jl`. I haven't tested this for a while though.

If you set `debug=True` you should be able to see the headers on the response from Storage when getting data and it should say something like `Content-Encoding: gzip`

**Comment by jingpengw** [comment]
thanks. It is pretty slow to use zlib to do gzip compression. Blosc support parallel compression and decompression and is more cache friendly. 
It seems that I can not do compression and decompression on my own side. 

The gzip flag should only set the header and do not do any compression? I can make a PR for this if you think that this is better.
Or we can add another option flag to really do compression or not. It can be true in default, so it will be backward compatible.

**Comment by jingpengw** [comment]
the PR was merged, so close here.
