### ISSUE TITLE
A home for GoogleCloud.jl

### ISSUE THREAD

**Issue by joshbode** [JuliaCloud/GoogleCloud.jl#22]
I'm not currently developing for Julia, or updating this package.
That's right, I'm one of those neglectful package owners I used to despise ;)

If people find this package useful and would like to continue its development, I think we should find a new home for it, possibly in [JuliaCloud](https://github.com/JuliaCloud).
If it would be accepted there, I'd be happy to migrate it.

cc: @StefanKarpinski, @tanmaykm, @JockLawrie

**Comment by JockLawrie** [comment]
I use Julia heavily, but not GoogleCloud.jl. Happy for the latter to find a new home/maintainer.

**Comment by StefanKarpinski** [comment]
JuliaCloud seems like the natural place to have it. @joshbode, I'll add you to the org so you can move it and continue to merge PRs on the project if you want to.

**Comment by joshbode** [comment]
Thanks @StefanKarpinski :)
I'll probably finish out these PRs and then move

**Comment by jingpengw** [comment]
I would like to do some basic maintenance of this package. @StefanKarpinski could you also add me to the org. I am a user of AWSCore.jl  and AWSSDK.jl too.

**Comment by StefanKarpinski** [comment]
@joshbode needs to transfer the repo to JuliaCloud first.

**Comment by joshbode** [comment]
Done :)

**Comment by joshbode** [comment]
Don't forget to update your URLs:
```
$ git remote set-url origin git@github.com:JuliaCloud/GoogleCloud.jl.git
```

**Comment by StefanKarpinski** [comment]
GitHub will redirect so it should be transparent to people.

**Comment by joshbode** [comment]
Ahh, great!

**Comment by StefanKarpinski** [comment]
What about now?

**Comment by jingpengw** [comment]
thanks, good now. close here.

**Comment by StefanKarpinski** [comment]
For some reason GitHub defaults to members only having read access to the repos in an org... which I guess might make sense for proprietary orgs, but makes zero sense for open source orgs since everyone can see the code already.
