### ISSUE TITLE
Update release tag to v0.8.0 so that Travis passes

### ISSUE THREAD

**Issue by JockLawrie** [JuliaCloud/GoogleCloud.jl#28]
Hi there,

v0.7.2 is failing on Travis with this error:

```
ERROR: LoadError: New tag 0.7.2 of package GoogleCloud requires julia 1.0.0, but version 0.7.1 of GoogleCloud requires julia 0.7.0. Use a new minor package version when support for an old version of Julia is dropped.
```

Seems that Travis requires a new minor version (v0.8.x instead of v0.7.x) because GoogleCloud.jl now requires Julia 1.0 whereas the previous version requires Julia 0.7. Could you pllease try tagging v0.8.0? Hopefully this will fix the Travis failure and the new release of GoogleCloud.jl will be automatically registered.

**Comment by jingpengw** [comment]
thanks for the notice. I just created a new release:
https://github.com/JuliaLang/METADATA.jl/pull/19731

**Comment by JockLawrie** [comment]
No worries, thank you too.

**Comment by jingpengw** [comment]
the PR was merged.
